---
languages:
  cpp:
    build: g++ -g %s -o a.out
    run: ./a.out
  rb:
    run: ruby %s
xpaths:
  sample_site:
    description: //div[@id="description"]
    inputs:
      - //div[@id="inputs"]/pre
    outputs:
      - //div[@id="outputs"]/pre
  aoj:
    description: //div[@class="description"]
    inputs:
      - //*[self::pre or self::div/pre][preceding-sibling::*[self::h2 or self::h3][1][contains(text(), "Sample Input") and not(contains(text(), "Output for the Sample Input"))]]
    outputs:
      - //*[self::pre or self::div/pre][preceding-sibling::*[self::h2 or self::h3][1][contains(text(), "Output for the Sample Input")]]
  atcoder:
    description: //div[@id="task-statement"]
    inputs:
      - //section[preceding-sibling::h3[1][contains(text(), "入力例")]]/pre
      - //pre[preceding-sibling::h3[1][contains(text(), "入力例")]]
    outputs:
      - //section[preceding-sibling::h3[1][contains(text(), "出力例")]]/pre
      - //pre[preceding-sibling::h3[1][contains(text(), "出力例")]]
